# Use root/example as user/password credentials
version: '3.9'

services:

  # postgres instance
  postgres:
    image: postgres
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres